name: Build and Test

on: 
  workflow_dispatch:
  push:
    paths:
      - "src/Transmitly/**"
      - "test/Transmitly.Teststest/**"
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: dotnet
        uses: actions/setup-dotnet@v3
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
      - name: Build netcore solution
        run: dotnet build Transmitly.sln /p:AssemblyVersion=${{ env.assemblySemVer }} /p:FileVersion=${{ env.assemblySemFileVer  }} /p:InformationalVersion=${{ env.informationalVersion }}
      - name: Build netframework solution
        run: |
          msbuild.exe Transmitly.sln /nologo /nr:false /p:configuration="Release" /p:AssemblyVersion=${{ env.assemblySemVer }} /p:FileVersion=${{ env.assemblySemFileVer  }} /p:InformationalVersion=${{ env.informationalVersion }}    
      - name: Test
        run: dotnet test --no-build --no-restore Transmitly.sln
      - name: Package
        run: dotnet pack --no-build --include-source /p:Version=${{ env.majorMinorPatch }}-dev+${{ env.shortSha }}
      - name: save package
        uses: actions/upload-artifact@v4
        with:
          name: pkg-test
          path: src/**/*.nupkg
        
