name: Release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
 
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
 #     - name: Verify commit exists in origin/main
 #       run: |
#            git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
#            git branch --remote --contains | grep origin/main
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: dotnet
        uses: actions/setup-dotnet@v3
      - name: Build netcore solution
        run: dotnet build Transmitly.sln --configuration Debug -p:AssemblyVersion=${VERSION} -p:FileVersion=${VERSION} -p:InformationalVersion=${VERSION}
      - name: Package
        run: dotnet pack Transmitly.sln --configuration Debug --no-build --include-source /p:Version=${VERSION} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
      - name: Publish Nuget
        run: dotnet nuget push .\src\Transmitly\bin\Debug\Transmitly.*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      - name: Add github source
        run: dotnet nuget add source --username ${{ secrets.PUBLISH_GITHUB_USERNAME }} --password ${{ secrets.PUBLISH_GITHUB_PACKAGE_API_KEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/transmitly/index.json"
      - name: Publish (Github)
        run: dotnet nuget push .\src\Transmitly\bin\Debug\Transmitly.*.nupkg --api-key ${{secrets.PUBLISH_GITHUB_PACKAGE_API_KEY}} --source "github"
